version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_testss
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    container_name: nextjs_testss
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      # Bind mount host folder so uploaded images persist on the host filesystem
      - ./public/interventionsPictures:/app/public/interventionsPictures
      - ./data:/app/data
    command: ["npm", "run", "start", "--", "-p", "3000", "-H", "0.0.0.0"]

volumes:
  postgres_data:
