version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_testss
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    container_name: nextjs_testss
    build:
      context: ./my-app
      dockerfile: ../Dockerfile
    restart: unless-stopped
    volumes:
      - ./my-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - postgres
    command: npm run dev

volumes:
  postgres_data:
